variables:
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    SLSA_PROVENANCE_SCHEMA_VERSION: "v1"

build-image:
    stage: "build"
    image: "docker:20.10.16"
    services:
      - "docker:20.10.16-dind"
    script:
      - "cd $IMAGE"
      - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
      - "docker build -t $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA -f Dockerfile ."
      - "docker push $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA"
    parallel:
        matrix:
          - IMAGE:
              - foldingathome
              - strelay
              - gitolite
