variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONDEVMODE: "1"
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    SLSA_PROVENANCE_SCHEMA_VERSION: "v1"

cache:
    paths:
      - ".cache/pip"

build-image-gitolite:
    stage: "build"
    needs:
      - "lint"
    image: "docker:20.10.16"
    services:
      - "docker:20.10.16-dind"
    script:
      - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
      - "docker build -t $CI_REGISTRY_IMAGE/gitolite:$CI_COMMIT_SHA -f Dockerfile ."
      - "docker push $CI_REGISTRY_IMAGE/gitolite:$CI_COMMIT_SHA"
